### ISSUE TITLE
Youtube: too many requests

### ISSUE THREAD

**Issue by edsu** [snarfed/huffduff-video#37]
When I try to use huffduffer to add a Youtube video I get this error:

<img width="472" alt="Screen Shot 2019-09-23 at 5 23 41 AM" src="https://user-images.githubusercontent.com/33829/65414802-69cdce00-ddc2-11e9-9f55-994a62448b41.png">

**Comment by snarfed** [comment]
sorry for the trouble, ed! cc @adactio. looks like this is due to to new IP-based throttling that youtube added in july:
* https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
* https://github.com/ytdl-org/youtube-dl/issues/21729
* https://torrentfreak.com/youtube-blocks-popular-mp3-stream-ripping-sites-190710/

i don't have an easy way to avoid this altogether, but i can definitely start by at least improving the error message. will do.

**Comment by ahope1** [comment]
I'm getting a slightly different variant of that error message

> When I try to use huffduffer to add a Youtube video I get this error: ...

I'm getting a slightly different version of that error message:

> Fetching https://www.youtube.com/watch?v=2UpMv2PHURo ...
> ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by ); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by snarfed** [comment]
hmm! it worked ok for me with a YouTube video just now. maybe transient?

**Comment by ahope1** [comment]
> hmm! it worked ok for me with a YouTube video just now. maybe transient?

Yes, it's working now!
